### ISSUE TITLE
Incorrect resistors listed in component list for Chapter 4 (led + button)

### ISSUE THREAD

**Issue by mhldr** [Freenove/Freenove_Ultimate_Starter_Kit_for_microbit#1]
Page 51 of the guide has the component list for "Control LED by Button"
This lists 2 x 10kΩ resistors and 1 x 220Ω resistor.

The subsequent pages actually require 3 x 220Ω resistors. 

If a child creates the circuit for chapter 3 and then is handed the extra components needed for Chapter 4 including two 10KΩ resistors they'll use them as R1 & R2 in the schematic on page 53... and the circuit will fail to function.

It's a harsh lesson to tell them to double check the resistor values in the circuit.

**Comment by DenzelChen** [comment]
Dear customer,
We are sorry to reply you so late. It is more convenient to contact us via support@freenove.com
Now there shoule be two 1KΩ resistors and one 220Ω resistor.
Sincerely,
Freenove Support Team
